const mahasiswa = [
    "Ade Mansyah Putra Tarigan",
    "Adinda Aulia",
    "Agnes Harefa Panjaitan",
    "Ahmad Fadhli",
    "Alfrido Cristina Sinaga",
    "Andrea Saputra Barus",
    "Anita Br Tarigan",
    "Apriliani Br Surbakti",
    "Arif Riansyah Lubis",
    "Benny Joseph",
    "Catur Riansyah Wicaksono",
    "Chania Dwi Marsha Br Barus",
    "Chrisna Rizky Fernando Sirait",
    "Christian Geovany Paulo Sinurat",
    "Christine Debora Simatupang",
    "Daniel Alfrido Adongma Sinaga",
    "Debby Christin Napitupulu",
    "Dewita Khaidiryanti",
    "Dila Safira",
    "Dira Salwaa Khairunnisa",
    "Egy Kurniawan",
    "Feklis Dermawan Laia",
    "Firman Giovanni Saragih",
    "Fransisco Purba",
    "Hafiznur Rasa Hasibuan",
    "Hiskya B Sinulingga",
    "Hosea Pieterson Sianturi",
    "Ima Putri Ambarita",
    "Inggid Safdina Aswa",
    "Jessica Heliani S ",
    "Joe Risky Ramadhan",
    "Julianus El Roy Ginting",
    "Kelvin",
    "Kidron Roberto Harahap",
    "Leandro Norbertus Karo Karo",
    "Meyzha Auriza",
    "Natanael H Sibagariang",
    "Nova Angelica Sinabariba",
    "Poda Theo Hamonangan Perangin Angin",
    "Priska Rasbina Br Ginting",
    "Putra Rapahan Tarigan",
    "Qofka Khoffia",
    "Qorimah",
    "Rahel Sakinah Assyifa",
    "Rian Syahputra",
    "Rudangta Barus",
    "S. L. Novita Lumbantoruan",
    "Salma Monita Latupong",
    "Sifra Artha Mulia Manalu",
    "Siti Fatimah",
    "Steven Nistel Remy Tambunan",
    "Tri Aditya Pramudita",
    "Tasifra Hasanah Hidayani",
    "Yediza Aprilia Br Hutapea"
];

export default mahasiswa;